- name: if conditions validation
  hosts: local
  connection: local
  vars:
    number: 18
    num: 6
  tasks:
    - name: print if number is greater than 10
      ansible.builtin.debug:
        msg: "The number is : {{number}} greater than 10"
      when: number > 10 
    - name: print if number is less than 10
      ansible.builtin.debug:
        msg: "The num is : {{num}} less than 10"
      when: num <= 10 