- name: different data types
  hosts: local
  connection: local
  vars:
    course_name: "Devops with AWS"
    duration: 110hrs
    topics: # list item
      - linux
      - terraform
      - ansible
    offline_class: false. #boolean
    tools_learnt:
      ci : jenkins
      cd : ansible
      cloud : AWS
  tasks:
   - name : print the data types
     ansible.builtin.debug:
      msg: "Hi all, the course_name is : {{course_name}} , duration is {{duration}} , topics covered are
        {{topics}} , offline classes are held {{offline_class}} , tools learnt {{tools_learnt}}"