[web]
172.31.18.190 COURSE="devops with AWS" DURATION=150hrs ansible_user=ec2-user ansible_password=DevOps321
[local]
localhost COURSE="devops with A1" DURATION=110hrs
[local:vars]
COURSE="DEVOPS with A2"
DURATION=115HRS