[web]
172.31.18.190 COURSE="devops with AWS" DURATION=150hrs ansible_user=ec2-user ansible_password=DevOps321
[local]
localhost 
; COURSE="devops with Azure" DURATION=180hrs
[local:vars]
COURSE="DEVOPS"
DURATION=120HRS