- name: variables passing
  hosts: local
  connection: local
  # vars:
  #    COURSE: "Devops with AWS"
  #    DURATION: 150hrs
 # vars_files:
 # - course.yaml
  # vars_prompt:
  #   - name: COURSE
  #     prompt: enter the course name      
  #   - name: DURATION
  #     prompt: enter the course duration   
  tasks:
    - name: print the variables from task1
      vars:
        COURSE: "Devops Only"
        DURATION: 120hrs 
      ansible.builtin.debug:
        msg: "The course is : {{COURSE}} and duration is : {{DURATION}} "
    - name: print the variables from task2
      ansible.builtin.debug:
        msg: "The course is : {{COURSE}} and duration is : {{DURATION}} "

# 1. passing arguments --> I passed only Course, no errors for duration but course is taken from here
# 2. Task  variable of 120hrs printed 
# 3. vars_file has 180 hrs which is taken next priority
# 4. vars_prompt has next priority
# 5. vars has next priority