- name: variables passing
  hosts: local
  connection: local
  vars:
     COURSE: "Devops with AWS"
     DURATION: 150hs
  tasks:
    - name: print the variables
    ansible.builtin.debug:
      msg: "The course is : {{COURSE} and duration is : {{DURATION}} }"