- name: variables in prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: course
      prompt: enter the course name
    - name: duration
      prompt: enter course duration
      private: false    # this will show the value what we enter on screen without hiding
    - name: instructor
      prompt: enter the instructor name 
  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "The course is : {{COURSE} and duration is : {{DURATION}} }"